### PR TITLE
New feature: select monitor (#38)

### PR DESCRIPTION
**Pull request by daltomi**
Ref: #38 
New option: `--monitor`, `-M`

- First attempt with `libxrandr`, temporarily discarded
- Second attempt with `libxinerama`, simpler API.

Example: `scrot -M 8` (force to fail, see log)

### CODE REVIEW

**Comment by daltomi** [comment]
It is a draft. 
This is a very old branch but `autotools` is configured correctly.
Resolving all conflicts with the `master branch` will never be done.

**Comment by daltomi** [comment]
To test `xrandr`:
```bash
git checkout -b xrandr 0a23c77
```

**Comment by ifohancroft** [comment]
I'm very happy to see that someone is working on this!

What was your reason for discarding the libxrandr method btw?

**Comment by daltomi** [comment]
It just seems to me that Xinerama is simpler to use. For now it works in the tests I did.

**Comment by ifohancroft** [comment]
> It just seems to me that Xinerama is simpler to use. For now it works in the tests I did.

To be honest, I was suprised it works with Xinerama without the monitors being in Xinerama mode (where each monitor is on its own X server). Unless of course I am mixing up terms.

**Pull request closed without merging**
