### PR TITLE
WIP: Implemented draw text in the capture.

### PR DESCRIPTION
**Pull request by daltomi**
Alpha testing.

New option: `-n` or `--note`

```bash
 ./scrot -n "f=FreeMonoBold/30:x=100:y=20:t=Hi scrot\!\!" -s 

 f= font_name/size (Imlib2 API)
 x= position x
 y= position y
 t= text
```
draw_text

TODO:

- [ ]  manpage
- [ ]  color text
- [ ] orientation,left,up,down,right
- [ ] background color, draw rectangle 
- [ ] user define font path. requirement

### CODE REVIEW

**Comment by daltomi** [comment]
Hi @eribertomota 

It seems that the git history was rewritten.

I'm not an expert on Git, but I think this happens when using `git rebase`
["The golden rule of git rebase is to never use it on public branches."](https://www.atlassian.com/git/tutorials/merging-vs-rebasing)
I do not use git rebase, do you?

Now, my local branch it no longer matches with the remote one. I delete this branch and then upload another updated one.

Regards.

**Comment by eribertomota** [comment]
Sorry! I do not expert too. I did a rebase to change a previous wrong
commit message.

Em ter, 11 de jun de 2019 às 12:03, Daniel T. Borelli <
notifications@github.com> escreveu:

**Comment by eribertomota** [comment]
I think you can copy all files to project and use git diff to see if I
changed anything after you.

Em ter, 11 de jun de 2019 às 13:11, Eriberto <eriberto@eriberto.pro.br>
escreveu:

**Comment by eribertomota** [comment]
I changed the Makefile.am. Please, update it in your branch.


Em ter, 11 de jun de 2019 às 13:13, Eriberto <eriberto@eriberto.pro.br>
escreveu:

**Pull request closed without merging**
