### PR TITLE
autotools improvement

### PR DESCRIPTION
**Pull request by daltomi**
This PR is a draft, it is intended for testing only.

This PR seeks to include improvements in the `autotools` build system:
 - Improvement in the detection of functions, libraries, etc.
 - Remove forced compiler directives such as directory inclusion(`-I.`) and manually entered library names(`-lX11`), see `Makefile.am`

**To be clear, compatibility with old versions of autotools should not be broken.  It is not my intention.**

This is why I omit some warnings like:

```bash
configure.ac:6: warning: The macro `AC_CONFIG_HEADER' is obsolete.
configure.ac:6: You should run autoupdate.
configure.ac:11: warning: 'AM_PROG_CC_STDC': this macro is obsolete.
configure.ac:11: You should simply use the 'AC_PROG_CC' macro instead.
```
---

If you want to test, please report what version of `autoconf` and `automake` you use and of course, if you had a successful compilation.

```
ArtixLinux - x86_64
automake - 1.16.3-1
autoconf - 2.71-1
```

Steps to test: 
```bash
$ git clone --single-branch https://github.com/resurrecting-open-source-projects/scrot.git

$ cd scrot

$ git remote add daltomi https://github.com/daltomi/scrot.git

$ git fetch daltomi

$ git checkout -b autotools-improvement-draft daltomi/autotools-improvement-draft

$ make distclean; ./autogen.sh; ./configure --prefix=/usr && make

```
Cheers.

### CODE REVIEW

**Comment by guijan** [comment]
Fails on OpenBSD:

```
$ ./configure --prefix=/usr
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking whether clang understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of clang... gcc3
checking for gcc... (cached) clang
checking whether we are using the GNU C compiler... (cached) yes
checking whether clang accepts -g... (cached) yes
checking for clang option to accept ISO C89... (cached) none needed
checking whether clang understands -c and -o together... (cached) yes
checking dependency style of clang... (cached) gcc3
checking whether make sets $(MAKE)... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for imlib2-config... /usr/local/bin/imlib2-config
checking for Imlib2... yes
checking for XOpenDisplay in -lX11... no
configure: error: required library are not present.
```

This seems to be because libX11 is in /usr/X11R6/lib on this system, the old automake definitions hardcoded that directory. pkg-config can be used to find it for us: https://autotools.io/pkgconfig/pkg_check_modules.html

**Comment by daltomi** [comment]
When I did this PR I didn't think about this. I don't know about BSD systems, currently I installed NetBSD(9.2) on a free partition that I had. I tried to compile even with the `master branch`(**this is important to note**) and got errors like yours, which couldn't find the libraries.

There are many things they do to compile than just using autotools, see [NetBSD -scrot Makefile](https://github.com/NetBSD/pkgsrc/blob/trunk/graphics/scrot/Makefile)

IMHO, in order not to work too hard with this PR that is to say the following:
Since this is a `GNU/Debian` maintained project, I don't know if it's our job to make implementations so that it works on each and every system out there. 
While we could use `PKG_CHECK_MODULES` I don't know if it will be enough for those systems.
If the macro `AC_CHECK_LIB` fails for them, the macro `PKG_CHECK_MODULES` could also fail.

**Comment by daltomi** [comment]
@guijan Can you confirm that in OpenBSD, and in the `master branch` it compiles successfully?
If so, I plan to close this PR.

**Comment by guijan** [comment]
The latest master compiles on OpenBSD just fine, here's a full build log:
[./autogen](https://paste.opensuse.org/view/raw/0eca5ae9)
[./configure](https://paste.opensuse.org/view/raw/d9263ce0)
[make](https://paste.opensuse.org/view/raw/47009d79)

But don't give up just yet, I've sent a patch to daltomi:autotools-improvement-draft which should fix the build.

**Comment by daltomi** [comment]
Perfect! works on NetBSD too :-)
Thanks!



TODO: (I leave this so as not to forget, I am going on a trip.)
- [ ] Add copyright notice: Makefile.am
- [ ] Notify of new dependency in README: `pkg-config`

**Comment by daltomi** [comment]
So far so good.

Resume:

| M4 |  Provider | Result | OS tested |
|-----|----------|--------|-----|
| `AC_CHECK_LIB` | autotools | OK | ArtixLinux |
| `AC_CHECK_LIB` | autotools | Failure | OpenBSD, NetBSD|
| `AC_SEARCH_LIBS` | autotools | Failure | NetBSD |
| `PKG_CHECK_MODULES` | pkg-config | OK | OpenBSD, NetBSD, ArtixLinux [+ 17 successful checks Cirrus CI](https://github.com/resurrecting-open-source-projects/scrot/pull/97/checks?check_run_id=3099848559) |

Best result: `PKG_CHECK_MODULES`

**Comment by daltomi** [comment]
Hey everyone,

 @eribertomota  I point out to you that this PR went from being a draft to a candidate to merge.
 This PR implies a new dependency: `pkg-config`, do you agree with this? and in general, with all this PR?
 Btw, currently [xorg itself uses `pkg-config`](https://www.x.org/wiki/NewModuleGuidelines/)

If you give me the ok I will merge and if you wish you can create a new release, thank you.

@guijan Thanks for the help!!

Cheers.

`squash-and-merge` what do I intend, since it was a draft I indicate the most important:
```
autotools improvement

Improvement in the detection of functions and libraries.
Add a new dependency for autotools: pkg-config

- configure.ac, Makefile.am: First improvements: add new macros, use the macro AC_CHECK_LIB
Signed-off-by: Daniel T. Borelli <daltomi@disroot.org>

- configure.ac, Makefile.am: Replace AC_CHECK_LIB macro with PKG_CHECK_MODULES
- README.md: Add pkg-config to dependency list
Signed-off-by: Guilherme Janczak <guilherme.janczak@yandex.com>
```

**Comment by guijan** [comment]
Is it really necessary to check the existence of these functions and headers and error out in the build system? If they're not present, there'll be a compilation error down the line.

Compilation of a test file with the contents ```int main(void) { void *bar; foo(bar); }```:

```
$ clang -o test test.c
test.c:5:2: warning: implicit declaration of function 'foo' is invalid in C99
      [-Wimplicit-function-declaration]
        foo(bar);
        ^
1 warning generated.
ld: error: undefined symbol: foo
>>> referenced by test.c
>>>               /tmp/test-38e596.o:(main)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by daltomi** [comment]
Well, it is not expected that a project that uses `autotools` works that way :-)

It is recommended by `autoscan` (surely the most problematic functions), I add some more functions (getopt*) and a fatal error since, IMO these functions should exist. We could change it to a non-fatal warning if necessary.

On the other hand if it fails we have the `config.log` file since a function can fail for another reason besides that it is not found (it says `autoconf` in his manual)

Are you seeing any future problems to implement `libbsd` for this PR?

**Comment by guijan** [comment]
Implementing libbsd will be trivial with pkg-config, this patch is perfect for it as is.

**Comment by eribertomota** [comment]
> Hey everyone,
> 
> @eribertomota I point out to you that this PR went from being a draft to a candidate to merge.
> This PR implies a new dependency: `pkg-config`, do you agree with this? and in general, with all this PR?
> Btw, currently [xorg itself uses `pkg-config`](https://www.x.org/wiki/NewModuleGuidelines/)

No problem for me. I think it is good.

> If you give me the ok I will merge and if you wish you can create a new release, thank you.

I will try to release a new version in this weekend. However, I saw several changes in source code and I need help with the changelog (only a draft about changes in C code; if you are able to help, you can put a list below). Thanks in advance.

**Comment by daltomi** [comment]
> I will try to release a new version in this weekend. However, I saw several changes in source code and I need help with the changelog (only a draft about changes in C code; if you are able to help, you can put a list below). Thanks in advance.

Hi,

Some commits of mine are missing but they are minor changes so I skipped them.
The biggest change is that `scrot` no longer depends on the `giblib` library and
depends on `pkg-config` to `autotools`

Saludos.
```
Draft (I indicate the nickname alias just to help you)

[ Shawn Webb ] alias @lattera
- Fixed Control Flow Integrity complain in HardenedBSD

[ Martin C  ] alias @Cationiz3r
- New feature: change the cursor pointer according to the movement of the selection

[ Christopher R. Nelson ] alias @languidnights 
- Remove dependence on giblib library

[ Guilherme Janczak ] alias @guijan 
- Removed the local implementation function: strdup
- Removed the local implementation function: getopt_long
- Removed unused file debug.h

[ Daniel T. Borelli ] alias @daltomi
- Fixed the capture when a window is hidden behind another
- Fixed the capture of the edge of the focused window
- Avoid capturing the selection box when drag and drop quickly
- Fixed issue when selection reaches the end of screen	
- New feature: resize the selection with the arrow keys
- New feature: support script Imlib2 commands
- New feature: added WM_CLASS to exclude selection mode edge from some composite window managers
- Improvement: selection option, capture the mouse cursor when the delay option is used
- Removed forced compiler options: -g -O3
```

**Pull request merged**
