### PR TITLE
WIP: Issue #12

### LINKED ISSUE #12: Provide with a way to prevent screenshots from being overwriten
This is a feature requested via bug[1] from a Debian user.

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=807139

The original Debian bug says:

------
Hello.

I have assigned the PrtScr key on my window manager
to the following bind:
scrot -q -z 'scrot_%Y%m%d_%H%M%S.png -e 'mv $f ~/Desktop'
which works absolutely fine.

However if there are more than one screenshots made
in the same second the file are being overwriten and
only the last one will remain.

There should be:
- an option to prevent/allow files to be overwritten
- if the option is set to not to overwrite files,
  a increment number could be appended to the file.
--------

Regards,

Eriberto

### PR DESCRIPTION
**Pull request by daltomi**
This try to fix #12 

New option: `-o` or `--overwrite`
~~Default: 1 (overwrite)~~
Default: 0
Try not to overwrite the file. If the file exists, add the format `file_000.ext` , `file_001.ext` ....

TODO:

- [x] manpage

### CODE REVIEW

**Comment by daltomi** [comment]
Now that I think about it better, maybe scrot by default should **not overwrite** the files and use `--overwrite` in a positive way.

Suggestions?

**Comment by daltomi** [comment]
For testing:
```bash
./scrot & ./scrot
```
Result:
```
2019-06-10-122220_1366x768_scrot.png
2019-06-10-122220_1366x768_scrot_000.png
```

**Comment by eribertomota** [comment]
Em seg, 10 de jun de 2019 às 12:25, Daniel T. Borelli
<notifications@github.com> escreveu:
>
> For testing:
>
> ./scrot & ./scrot
>
> Result:
>
> 2019-06-10-122220_1366x768_scrot.png
> 2019-06-10-122220_1366x768_scrot_000.png


Very good! When you merge, I will release a new version.

Eriberto

**Comment by SrTobi** [comment]
setting this behavior as default broke my workflow

In i3, I had 
```
bindsym --release $mod+Print exec scrot -s ~/store/pictures/screenshot.png && xclip -selection clipboard -t image/png -i ~/store/pictures/screenshot.png
```
with the changes this copies the old picture over and over again

**Pull request merged**
