### PR TITLE
Include the giblib project source files.

### PR DESCRIPTION
**Pull request by daltomi**
Hi all,

There are approximately ~30 calls to giblib functions. So I think it is best to include it in the scrot project that is reinventing the wheel.

This PR add `src/giblib`  folder with the sources files and standard autotools files: README, AUTHORS, etc.

Regards.

### CODE REVIEW

**Comment by eribertomota** [comment]
Hi @daltomi,

Sorry, but I fully disagree. Embedded libraries require extra effort to security maintenance or normal maintenance. It is strongly abominated in Debian. Our Lintian system always points it as an error. Please, see the following texts:

https://www.debian.org/doc/debian-policy/ch-source.html#convenience-copies-of-code
https://wiki.debian.org/UpstreamGuide#No_inclusion_of_third_party_code
https://lintian.debian.org/tags/embedded-library.html

Thanks!

Cheers,

Eriberto

**Comment by daltomi** [comment]
You're right, thanks for indicating this.
Cheers.

**Comment by eribertomota** [comment]
Thank you!

Em seg, 5 de ago de 2019 às 20:04, Daniel T. Borelli <
notifications@github.com> escreveu:

**Comment by mathstuf** [comment]
@eribertomota In Fedora at least, giblib is *only* used by scrot. Upstream is dead and, AFAIK, nothing else uses it, so this might be a reasonable solution anyways.  Is giblib used in any other capacity in Debian?

**Comment by jda** [comment]
For what it's worth, giblib has already been vendored by other projects. For example, feh: https://github.com/derf/feh/blob/master/src/gib_imlib.h

Looking at how scrot uses giblib I don't think we're getting that much from it, so we may as well remove it entirely.

**Comment by eribertomota** [comment]
Hi folks,

@mathstuf, in Debian scrot and gozer depend of giblib.

@jda, can you try remove?

Cheers,

Eriberto

**Comment by jda** [comment]
@eribertomota, yes :)
Only part that remains in my branch is the linked list handling. I'm trying to replace that with `sys/queue.h` (more discussion on #22 )

**Pull request closed without merging**
