### PR TITLE
fix libbsd feature test confusion

### PR DESCRIPTION
**Pull request by guijan**
Users expressed confusion when using the old "--without-libbsd" configure flag. Some assumed that it compiles scrot without libbsd, but it only made the build script error if libbsd is a dependency. This is useful to package maintainers: it gives them a yes/no answer on whether the library is a dependency on their system.

The old configure flag has been replaced by a more verbose "--enable-libbsd-feature-test".

See: https://github.com/resurrecting-open-source-projects/scrot/issues/208 https://github.com/resurrecting-open-source-projects/scrot/discussions/187

I've tested the yes/no paths using Alpine Linux and OpenBSD.

### CODE REVIEW

**Comment by daltomi** [comment]
Let's hope no one reads fast and doesn't see the `-test` at the end, because it also looks like you're enabling the libbsd library features: "If I enable libbsd it will be more secure"(or something like that)
But if you prefer as it is we leave it like that.

**Comment by eribertomota** [comment]
I will wait for this change to release the 1.8.1 version.

**Comment by daltomi** [comment]
> But if you prefer as it is we leave it like that.

Hi @guijan
Please, if you can, confirm that you do not want to make changes to this PR, thank you.

**Comment by guijan** [comment]
Hi, yes, the PR is finished, I don't intend to change it.

**Comment by daltomi** [comment]
@eribertomota all ready to merge then, FYI this PR should close at #208 (Can we avoid libbsd?), thanks you.

**Comment by eribertomota** [comment]
> @eribertomota all ready to merge then, FYI this PR should close at #208 (Can we avoid libbsd?), thanks you.

Thanks, @daltomi.

**Pull request merged**
